
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('1', 'positivo', 'Una lectura maravillosa que me mantuvo enganchado desde la primera página.', '1', '1');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('2', 'positivo', 'Me encanta la evolución de la trama en este libro. Muy bien escrito.', '2', '2');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('3', 'neutral', 'Un buen libro, pero no tan emocionante como el anterior.', '3', '3');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('4', 'positivo', 'Un libro emocionante y lleno de sorpresas. Gran continuación de la saga.', '4', '4');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('5', 'negativo', 'Demasiado predecible y con personajes planos. No cumplió mis expectativas.', '5', '5');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('6', 'negativo', 'El ritmo es muy lento y la trama se siente forzada. No lo recomendaría.', '6', '6');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('7', 'negativo', 'La historia se vuelve repetitiva y poco original. Esperaba más.', '7', '7');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('8', 'negativo', 'El final fue muy anticlimático y no resolvió bien la trama.', '8', '8');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('9', 'positivo', 'Una historia fantástica con un mundo ricamente detallado. Me encantó.', '9', '9');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('10', 'positivo', 'Un inicio épico para una trilogía increíble. El mundo de la Tierra Media es fascinante.', '10', '10');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('11', 'positivo', 'Una secuela emocionante con una gran expansión del mundo y la trama.', '11', '11');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('12', 'positivo', 'Un final épico para una saga inolvidable. Excelente conclusión.', '12', '12');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('13', 'negativo', 'Demasiado largo y detallado. La historia se perdió en detalles innecesarios.', '13', '13');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('14', 'negativo', 'El ritmo es muy lento y la trama se siente estirada. No logró mantener mi interés.', '14', '14');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('15', 'negativo', 'Demasiados personajes y subtramas. Resulta confuso y difícil de seguir.', '15', '15');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('16', 'negativo', 'El final fue decepcionante y no cerró bien la saga.', '16', '16');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('17', 'positivo', 'Un libro aterrador que me mantuvo despierto por las noches. Excelente.', '17', '17');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('18', 'positivo', 'Una historia de horror psicológico muy bien escrita. Absolutamente recomendada.', '18', '18');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('19', 'neutral', 'Un libro interesante pero un poco largo. La historia es buena, aunque podría ser más concisa.', '19', '19');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('20', 'positivo', 'Un thriller psicológico impresionante con un gran desarrollo de personajes.', '20', '20');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('21', 'negativo', 'Demasiado extenso y con una trama que se siente repetitiva en ocasiones.', '21', '21');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('22', 'negativo', 'El ritmo es irregular y el final no es satisfactorio.', '22', '22');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('23', 'negativo', 'La historia es interesante, pero el desarrollo es muy lento y a veces aburrido.', '23', '23');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('24', 'negativo', 'El desarrollo de los personajes no es tan fuerte como esperaba. Un poco decepcionante.', '24', '24');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('25', 'positivo', 'Una trama intrigante con un giro inesperado al final. Clásico de Christie.', '25', '25');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('26', 'positivo', 'Un misterio bien desarrollado en un entorno exótico. Muy entretenido.', '26', '26');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('27', 'positivo', 'Un misterio de asesinato clásico con una resolución sorprendente.', '27', '27');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('28', 'neutral', 'Un buen misterio, pero la resolución no fue tan impactante como esperaba.', '28', '28');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('29', 'negativo', 'El misterio fue predecible y la resolución no fue satisfactoria.', '29', '29');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('30', 'negativo', 'La trama se siente un poco estirada y el ritmo es lento.', '30', '30');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('32', 'negativo', 'La resolución del caso no fue tan impactante como esperaba.', '32', '32');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('33', 'positivo', 'Un inicio épico para una serie impresionante. Intrigas y traiciones en cada página.', '33', '33');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('34', 'positivo', 'Una continuación emocionante que expande la trama de manera impresionante.', '34', '34');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('35', 'positivo', 'Un libro lleno de acción y sorpresas. Una gran adición a la serie.', '35', '35');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('36', 'positivo', 'Una trama fascinante con muchos giros. Aún mejor que el anterior.', '36', '36');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('37', 'negativo', 'Demasiado extenso y con demasiadas subtramas que alargan innecesariamente la historia.', '37', '37');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('38', 'negativo', 'El ritmo es irregular y algunas tramas se sienten sin rumbo.', '38', '38');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('39', 'negativo', 'La narrativa se siente lenta en algunos puntos y el desarrollo de personajes es desigual.', '39', '39');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('40', 'negativo', 'El libro es largo y se siente repetitivo en comparación con los anteriores.', '40', '40');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('41', 'positivo', 'Un misterio clásico de Sherlock Holmes. Intriga y lógica en cada página.', '41', '41');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('42', 'positivo', 'Un gran caso de Holmes con una trama bien construida. Muy entretenido.', '42', '42');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('43', 'positivo', 'Una de las mejores historias de Sherlock Holmes. Intriga y suspense.', '43', '43');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('44', 'neutral', 'Una buena historia, pero no tan fuerte como otros casos de Holmes.', '44', '44');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('45', 'negativo', 'El misterio no es tan intrigante como otros casos de Holmes.', '45', '45');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('46', 'negativo', 'El ritmo es lento y la trama se siente un poco predecible.', '46', '46');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('47', 'negativo', 'La resolución del misterio fue decepcionante y no tan impactante como esperaba.', '47', '47');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('48', 'negativo', 'No me gustó tanto como otras historias de Sherlock Holmes.', '48', '48');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('49', 'positivo', 'Un clásico de la ciencia ficción con una trama muy original y bien desarrollada.', '49', '49');
INSERT INTO comentario (id, tipo, contenido, usuario_id, libro_id) VALUES ('50', 'positivo', 'Una continuación que expande la trama de manera efectiva. Muy bien escrito.', '50', '50');
