
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('1', 'Editorial Alfa', 'contacto@editorialalfa.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('2', 'Editorial Beta', 'info@editorialbeta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('3', 'Editorial Gamma', 'contact@editorialgamma.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('4', 'Editorial Delta', 'support@editorialdelta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('5', 'Editorial Epsilon', 'hello@editorialepsilon.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('6', 'Editorial Zeta', 'info@editorialzeta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('7', 'Editorial Eta', 'contact@editorialeta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('8', 'Editorial Theta', 'info@editorialtheta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('9', 'Editorial Iota', 'contact@editorialiota.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('10', 'Editorial Kappa', 'support@editorialkappa.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('11', 'Editorial Lambda', 'info@editoriallambda.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('12', 'Editorial Mu', 'contact@editorialmu.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('13', 'Editorial Nu', 'info@editorialnu.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('14', 'Editorial Xi', 'contact@editorialxi.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('15', 'Editorial Omicron', 'support@editorialomicron.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('16', 'Editorial Pi', 'info@editorialpi.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('17', 'Editorial Rho', 'contact@editorialrho.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('18', 'Editorial Sigma', 'info@editorialsigma.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('19', 'Editorial Tau', 'contact@editorialtau.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('20', 'Editorial Upsilon', 'support@editorialupsilon.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('21', 'Editorial Phi', 'info@editorialphi.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('22', 'Editorial Chi', 'contact@editorialchi.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('23', 'Editorial Psi', 'info@editorialpsi.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('24', 'Editorial Omega', 'contact@editorialomega.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('25', 'Editorial Alpha', 'info@editorialalpha.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('26', 'Editorial Beta', 'contact@editorialbeta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('27', 'Editorial Gamma', 'info@editorialgamma.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('28', 'Editorial Delta', 'contact@editorialdelta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('29', 'Editorial Epsilon', 'support@editorialepsilon.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('30', 'Editorial Zeta', 'info@editorialzeta.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('31', 'Bloomsbury', 'contact@bloomsbury.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('32', 'Allen  Unwin', 'info@allenandunwin.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('33', 'Scribner', 'editor@scribner.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('34', 'Collins Crime Club', 'info@collinscrimeclub.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('35', 'Bantam Books', 'contact@bantambooks.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('36', 'Arthur Conan Doyle Publishing', 'contact@acdpublishing.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('37', 'Gnome Press', 'info@gnomepress.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('38', 'Little, Brown and Company', 'info@littlebrown.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('39', 'T. Egerton', 'contact@tegerton.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('40', 'Chatto  Windus', 'contact@chatto-windus.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('41', 'Charles Scribners Sons', 'contact@scribners.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('42', 'Scribner', 'editor@scribner.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('43', 'Chapman  Hall', 'contact@chapmanhall.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('44', 'The Russian Messenger', 'info@russianmessenger.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('45', 'Harper  Brothers', 'editor@harperbrothers.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('46', 'Hogarth Press', 'contact@hogarthpress.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('47', 'The Dial Press', 'info@thedialpress.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('48', 'Kurt Wolff Verlag', 'contact@kurtwolff.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('49', 'Editorial Sudamericana', 'info@editorialsudamericana.com');
INSERT INTO editorial (id, nombre, correoElectronico) VALUES ('50', 'Emecé Editores', 'contact@emece.com');
