INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('1', 'Novela Clásica', 'Estante 1, Sección A', TO_DATE('2024-01-01', 'YYYY-MM-DD'), '1');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('2', 'Guías de Estudio', 'Estante 2, Sección B', TO_DATE('2024-01-02', 'YYYY-MM-DD'), '2');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('3', 'Diccionarios', 'Estante 3, Sección C', TO_DATE('2024-01-03', 'YYYY-MM-DD'), '3');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('4', 'Cuentos', 'Estante 4, Sección D', TO_DATE('2024-01-04', 'YYYY-MM-DD'), '4');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('5', 'Novela Juvenil', 'Estante 5, Sección E', TO_DATE('2024-01-05', 'YYYY-MM-DD'), '5');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('6', 'Libros de Texto', 'Estante 6, Sección F', TO_DATE('2024-01-06', 'YYYY-MM-DD'), '6');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('7', 'Obras de Arte', 'Estante 7, Sección G', TO_DATE('2024-01-07', 'YYYY-MM-DD'), '7');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('8', 'Manual de Tecnologías', 'Estante 8, Sección H', TO_DATE('2024-01-08', 'YYYY-MM-DD'), '8');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('9', 'Historia Antigua', 'Estante 9, Sección I', TO_DATE('2024-01-09', 'YYYY-MM-DD'), '9');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('10', 'Geografía Mundial', 'Estante 10, Sección J', TO_DATE('2024-01-10', 'YYYY-MM-DD'), '10');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('11', 'Poesía Contemporánea', 'Estante 11, Sección K', TO_DATE('2024-01-11', 'YYYY-MM-DD'), '11');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('12', 'Biografías de Científicos', 'Estante 12, Sección L', TO_DATE('2024-01-12', 'YYYY-MM-DD'), '12');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('13', 'Álgebra Avanzada', 'Estante 13, Sección M', TO_DATE('2024-01-13', 'YYYY-MM-DD'), '13');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('14', 'Gramática Española', 'Estante 14, Sección N', TO_DATE('2024-01-14', 'YYYY-MM-DD'), '14');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('15', 'Programación en Python', 'Estante 15, Sección O', TO_DATE('2024-01-15', 'YYYY-MM-DD'), '15');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('16', 'Introducción General', 'Estante 16, Sección P', TO_DATE('2024-01-16', 'YYYY-MM-DD'), '16');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('17', 'Revistas Académicas', 'Estante 17, Sección Q', TO_DATE('2024-01-17', 'YYYY-MM-DD'), '17');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('18', 'Espacios de Estudio', 'Estante 18, Sección R', TO_DATE('2024-01-18', 'YYYY-MM-DD'), '18');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('19', 'Publicaciones de Investigación', 'Estante 19, Sección S', TO_DATE('2024-01-19', 'YYYY-MM-DD'), '19');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('20', 'Material de Salud', 'Estante 20, Sección T', TO_DATE('2024-01-20', 'YYYY-MM-DD'), '20');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('21', 'Estudios Económicos', 'Estante 21, Sección U', TO_DATE('2024-01-21', 'YYYY-MM-DD'), '21');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('22', 'Derecho Comparado', 'Estante 22, Sección V', TO_DATE('2024-01-22', 'YYYY-MM-DD'), '22');
INSERT INTO subArea (id, nombre, ubicacion, año, area_id) VALUES ('23', 'Cultura Popular', 'Estante 23, Sección W', TO_DATE('2024-01-23', 'YYYY-MM-DD'), '23');
