
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('1', 'Pasta dura', 'El inicio de la saga mágica de Harry Potter.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('2', 'Pasta dura', 'Harry Potter descubre más secretos en Hogwarts.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('3', 'Pasta dura', 'Harry Potter enfrenta a Sirius Black.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('4', 'Pasta dura', 'Harry Potter compite en el Torneo de los Tres Magos.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('5', 'Pasta dura', 'La aventura de Bilbo Bolsón en la Tierra Media.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('6', 'Pasta dura', 'El comienzo de la travesía de Frodo Bolsón.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('7', 'Pasta dura', 'La continuación de la misión de destruir el Anillo.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('8', 'Pasta dura', 'La batalla final por la Tierra Media.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('9', 'Pasta blanda', 'La historia de Carrie White y su venganza.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('11', 'Pasta blanda', 'El enfrentamiento de un grupo de amigos contra Pennywise.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('12', 'Pasta blanda', 'Un escritor secuestrado por su fan número uno.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('13', 'Pasta blanda', 'Un asesinato en el famoso tren Orient Express.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('14', 'Pasta blanda', 'El misterio en el Nilo resuelto por Poirot.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('15', 'Pasta blanda', 'Diez personas en una isla, una trama de asesinato.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('16', 'Pasta blanda', 'Poirot resuelve el caso de Roger Ackroyd.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('17', 'Pasta dura', 'El inicio de la serie épica de George R.R. Martin.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('18', 'Pasta dura', 'La lucha por el Trono de Hierro continúa.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('19', 'Pasta dura', 'La guerra por el poder se intensifica.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('20', 'Pasta dura', 'Las secuelas de la guerra y las nuevas amenazas.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('21', 'Pasta blanda', 'El primer caso de Sherlock Holmes.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('23', 'Pasta blanda', 'Holmes investiga el misterio de los Baskerville.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('24', 'Pasta blanda', 'Una colección de historias cortas de Holmes.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('25', 'Pasta dura', 'La primera novela de la serie Fundación.', '18.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('26', 'Pasta dura', 'La continuación de la saga Fundación.', '18.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('27', 'Pasta dura', 'El cierre de la trilogía original de Fundación.', '18.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('28', 'Pasta dura', 'La historia de un robot que desea ser humano.', '18.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('30', 'Pasta dura', 'La historia de amor entre Elizabeth Bennet y Mr. Darcy.', '17.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('31', 'Pasta dura', 'Las hermanas Dashwood y su búsqueda del amor.', '17.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('32', 'Pasta dura', 'Las peripecias de Emma Woodhouse en su vida amorosa.', '17.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('33', 'Pasta dura', 'La última novela completa de Jane Austen.', '17.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('34', 'Pasta blanda', 'Las travesuras de Tom Sawyer en el sur de EE.UU.', '13.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('35', 'Pasta blanda', 'Las aventuras de Huckleberry Finn en el Mississippi.', '13.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('36', 'Pasta blanda', 'La lucha de un anciano pescador contra un pez gigante.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('37', 'Pasta blanda', 'La historia de amor y guerra en España.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('38', 'Pasta blanda', 'La trágica historia de un soldado en la Primera Guerra Mundial.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('39', 'Pasta blanda', 'Las aventuras del huérfano Oliver Twist en Londres.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('40', 'Pasta blanda', 'Un cuento de redención navideña.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('41', 'Pasta blanda', 'La vida de David Copperfield desde su infancia hasta la madurez.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('42', 'Pasta dura', 'Una épica novela sobre la invasión napoleónica en Rusia.', '24.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('43', 'Pasta dura', 'La historia de amor entre Anna Karenina y el conde Vronsky.', '24.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('44', 'Pasta dura', 'La obsesiva caza de una ballena blanca.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('46', 'Pasta blanda', 'Una familia de vacaciones en las Hébridas.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('47', 'Pasta blanda', 'La vida de seis personajes desde la infancia hasta la vejez.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('48', 'Pasta dura', 'El épico viaje de Leopold Bloom por Dublín.', '22.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('49', 'Pasta blanda', 'Una colección de relatos cortos sobre la vida en Dublín.', '13.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('50', 'Pasta blanda', 'La transformación de Gregor Samsa en un insecto gigante.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('51', 'Pasta blanda', 'La historia de Josef K. y su lucha contra un sistema judicial opresivo.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('52', 'Pasta dura', 'La saga épica de la familia Buendía en Macondo.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('53', 'Pasta dura', 'La historia de amor entre Fermina Daza y Florentino Ariza.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('54', 'Pasta blanda', 'Una colección de cuentos cortos llenos de imaginación.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('55', 'Pasta blanda', 'Una colección de cuentos cortos filosóficos.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('56', 'Pasta blanda', 'La historia de Mowgli, un niño criado por lobos.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('57', 'Pasta blanda', 'Las aventuras y problemas de las hermanas March.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('58', 'Pasta blanda', 'La trágica historia de amor en los páramos de Yorkshire.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('59', 'Pasta blanda', 'El romance entre Elizabeth Bennet y Mr. Darcy.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('60', 'Pasta blanda', 'La vida del misterioso Jay Gatsby.', '12.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('61', 'Pasta dura', 'Matar a un ruiseñor: Una joven se enfrenta a los prejuicios en el sur de los EE.UU.', '25.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('62', 'Pasta blanda', '1984: Un mundo distópico bajo la vigilancia del Gran Hermano.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('63', 'Pasta blanda', 'Rebelión en la granja: Una alegoría política sobre una granja de animales.', '14.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('64', 'Pasta dura', 'El señor de los anillos: La comunidad del anillo: Un grupo de amigos se embarca en una épica aventura.', '35.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('65', 'Pasta dura', 'El hobbit: Las aventuras de Bilbo Bolsón en la Tierra Media.', '29.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('66', 'Pasta blanda', 'El retrato de Dorian Gray: Un joven que vende su alma por la juventud eterna.', '17.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('67', 'Pasta dura', 'Drácula: La lucha contra el legendario vampiro Drácula.', '24.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('68', 'Pasta blanda', 'Cien años de soledad: La historia de la familia Buendía en Macondo.', '23.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('69', 'Pasta blanda', 'El amor en los tiempos del cólera: Un amor que perdura a lo largo de los años.', '21.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('70', 'Pasta dura', 'El código Da Vinci: Un thriller sobre misterios religiosos y secretos.', '27.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('71', 'Pasta dura', 'Ángeles y demonios: Una conspiración antigua que amenaza al Vaticano.', '26.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('72', 'Pasta blanda', 'Harry Potter y la piedra filosofal: El inicio de las aventuras de Harry Potter.', '22.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('73', 'Pasta blanda', 'Harry Potter y la cámara secreta: Harry Potter regresa a Hogwarts para su segundo año.', '23.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('74', 'Pasta dura', 'La casa de los espíritus: Una saga familiar en Chile con elementos mágicos.', '31.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('75', 'Pasta blanda', 'Paula: Una conmovedora memoria escrita por Isabel Allende.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('76', 'Pasta dura', 'Los pilares de la tierra: La construcción de una catedral en la Edad Media.', '34.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('77', 'Pasta dura', 'Un mundo sin fin: La continuación de la saga de "Los pilares de la tierra".', '36.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('78', 'Pasta blanda', 'El hombre en busca de sentido: La búsqueda del sentido de la vida en los campos de concentración.', '15.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('79', 'Pasta blanda', 'El arte de la felicidad: Lecciones sobre la felicidad por el Dalai Lama.', '18.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('80', 'Pasta blanda', 'El alquimista: Un pastor andaluz busca su leyenda personal.', '20.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('81', 'Pasta blanda', 'Veronika decide morir: Una joven enfrenta la vida tras un intento de suicidio.', '21.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('82', 'Pasta dura', 'El nombre de la rosa: Un misterio medieval en una abadía benedictina.', '28.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('83', 'Pasta dura', 'El péndulo de Foucault: Una compleja novela sobre conspiraciones y secretos.', '30.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('84', 'Pasta blanda', 'Los juegos del hambre: Una adolescente se convierte en símbolo de rebelión.', '22.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('85', 'Pasta blanda', 'En llamas: Katniss Everdeen lucha en una nueva arena.', '23.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('86', 'Pasta blanda', 'Mujeres que corren con los lobos: Exploraciones de la psique femenina y los mitos.', '24.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('87', 'Pasta blanda', 'El despertar de la serpiente: Aventuras y misterios en un mundo fantástico.', '21.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('88', 'Pasta blanda', 'El diario de Ana Frank: El diario de una joven durante la Segunda Guerra Mundial.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('89', 'Pasta dura', 'Los hermanos Karamazov: La vida y conflictos de una familia rusa.', '32.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('90', 'Pasta blanda', 'Cien años de soledad: La historia de la familia Buendía en Macondo.', '23.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('91', 'Pasta blanda', 'El amor en los tiempos del cólera: Un amor que perdura a lo largo de los años.', '21.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('92', 'Pasta dura', 'El código Da Vinci: Un thriller sobre misterios religiosos y secretos.', '27.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('93', 'Pasta dura', 'Ángeles y demonios: Una conspiración antigua que amenaza al Vaticano.', '26.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('94', 'Pasta blanda', 'Harry Potter y la piedra filosofal: El inicio de las aventuras de Harry Potter.', '22.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('95', 'Pasta blanda', 'Harry Potter y la cámara secreta: Harry Potter regresa a Hogwarts para su segundo año.', '23.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('96', 'Pasta dura', 'La casa de los espíritus: Una saga familiar en Chile con elementos mágicos.', '31.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('97', 'Pasta blanda', 'Paula: Una conmovedora memoria escrita por Isabel Allende.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('98', 'Pasta dura', 'La sombra del viento: Un joven descubre un libro que cambia su vida.', '29.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('99', 'Pasta dura', 'El juego del ángel: Un escritor lucha contra sus demonios en la Barcelona de los años 20.', '28.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('100', 'Pasta dura', 'El prisionero del cielo: Un misterio se desarrolla en el Cementerio de los Libros Olvidados.', '27.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('101', 'Pasta dura', 'El laberinto de los espíritus: El desenlace de la saga de "La sombra del viento".', '31.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('102', 'Pasta dura', 'Don Quijote de la Mancha: Las aventuras de Don Quijote y Sancho Panza.', '35.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('103', 'Pasta blanda', 'Cien años de soledad: La historia de la familia Buendía en Macondo.', '23.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('104', 'Pasta blanda', 'Rayuela: Una novela experimental que desafía las normas literarias.', '24.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('105', 'Pasta blanda', 'Crimen y castigo: La lucha moral de un hombre en San Petersburgo.', '26.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('106', 'Pasta blanda', 'Madame Bovary: La vida y pasiones de una mujer provinciana.', '24.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('107', 'Pasta dura', 'La guerra de los mundos: Una invasión marciana amenaza a la Tierra.', '22.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('108', 'Pasta dura', 'Los miserables: La vida de varios personajes en la Francia post-revolucionaria.', '34.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('109', 'Pasta dura', 'La divina comedia: El viaje de Dante a través del Infierno, el Purgatorio y el Paraíso.', '29.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('110', 'Pasta blanda', 'El principito: Un niño y su pequeño planeta en un viaje filosófico.', '20.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('111', 'Pasta blanda', 'Frankenstein: La creación de un monstruo y su lucha por la humanidad.', '19.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('112', 'Pasta dura', 'El Conde de Montecristo: La épica historia de venganza de Edmond Dantès.', '32.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('113', 'Pasta dura', 'La sombra del viento: Un joven descubre un libro que cambia su vida.', '29.99');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('314', 'pasta dura', 'Noticia de un secuestro es una novela escrita por el colombiano Gabriel García Márquez publicada por Grupo Editorial Norma en 1996.1​ Está basado en la historia real del secuestro de figuras prominentes de Colombia durante la época del narcoterrorismo a inicios de los años 1990 con la autoría de Los Extraditables.', '290');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('315', 'pasta dura', 'Noticia de un secuestro es una novela escrita por el colombiano Gabriel García Márquez publicada por Grupo Editorial Norma en 1996.1​ Está basado en la historia real del secuestro de figuras prominentes de Colombia durante la época del narcoterrorismo a inicios de los años 1990 con la autoría de Los Extraditables.', '290');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('316', 'pasta dura', 'Una vista guiada por las matemáticas del uno al infinito', '22');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('317', 'PASTA DURA', 'Un libro para estudiantes de ingniería.', '25');
INSERT INTO formatoLibro (id, tipo, observacion, precio) VALUES ('318', 'pasta dura', 'El libro Coraline nos sumerge en un entorno de fantasía y peligro a través de sus doce apasionantes capítulos. Neil Gaiman nos presenta a una protagonista valiente y decidida que debe enfrentarse a sus miedos y desafiar a la malvada otra madre. A lo largo de la historia, Coraline demuestra el poder del ingenio, la valentía y el amor familiar.', '30');
