INSERT INTO area (id, nombre, ubicacion) VALUES ('1', 'Ficción', 'Planta Baja, Ala Norte');
INSERT INTO area (id, nombre, ubicacion) VALUES ('2', 'No Ficción', 'Planta Baja, Ala Sur');
INSERT INTO area (id, nombre, ubicacion) VALUES ('3', 'Referencia', 'Primer Piso, Ala Este');
INSERT INTO area (id, nombre, ubicacion) VALUES ('4', 'Infantil', 'Planta Baja, Ala Oeste');
INSERT INTO area (id, nombre, ubicacion) VALUES ('5', 'Juvenil', 'Segundo Piso, Ala Norte');
INSERT INTO area (id, nombre, ubicacion) VALUES ('6', 'Ciencias', 'Segundo Piso, Ala Sur');
INSERT INTO area (id, nombre, ubicacion) VALUES ('7', 'Artes', 'Primer Piso, Ala Oeste');
INSERT INTO area (id, nombre, ubicacion) VALUES ('8', 'Tecnología', 'Segundo Piso, Ala Este');
INSERT INTO area (id, nombre, ubicacion) VALUES ('9', 'Historia', 'Tercer Piso, Ala Norte');
INSERT INTO area (id, nombre, ubicacion) VALUES ('10', 'Geografía', 'Tercer Piso, Ala Sur');
INSERT INTO area (id, nombre, ubicacion) VALUES ('11', 'Literatura', 'Tercer Piso, Ala Este');
INSERT INTO area (id, nombre, ubicacion) VALUES ('12', 'Biografías', 'Tercer Piso, Ala Oeste');
INSERT INTO area (id, nombre, ubicacion) VALUES ('13', 'Matemáticas', 'Primer Piso, Ala Norte');
INSERT INTO area (id, nombre, ubicacion) VALUES ('14', 'Español', 'Primer Piso, Ala Sur');
INSERT INTO area (id, nombre, ubicacion) VALUES ('15', 'Sistemas', 'Segundo Piso, Ala Central');
INSERT INTO area (id, nombre, ubicacion) VALUES ('16', 'General Universidad', 'Planta Baja, Ala Central');
INSERT INTO area (id, nombre, ubicacion) VALUES ('17', 'Sala de Lectura', 'Planta Baja, Ala Este');
INSERT INTO area (id, nombre, ubicacion) VALUES ('18', 'Sala de Estudio', 'Primer Piso, Ala Central');
INSERT INTO area (id, nombre, ubicacion) VALUES ('19', 'Investigación', 'Cuarto Piso, Ala Norte');
INSERT INTO area (id, nombre, ubicacion) VALUES ('20', 'Salud', 'Cuarto Piso, Ala Sur');
INSERT INTO area (id, nombre, ubicacion) VALUES ('21', 'Economía', 'Tercer Piso, Ala Este');
INSERT INTO area (id, nombre, ubicacion) VALUES ('22', 'Derecho', 'Tercer Piso, Ala Oeste');
INSERT INTO area (id, nombre, ubicacion) VALUES ('23', 'Cultura', 'Segundo Piso, Ala Oeste');