
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('1', 'LPS 20', TO_DATE('2024-01-10', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '30');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('2', 'LPS 100', TO_DATE('2024-01-11', 'YYYY-MM-DD'), 'No realizar el pago de libro', '31');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('3', 'LPS 200', TO_DATE('2024-01-12', 'YYYY-MM-DD'), 'Extraviar libro', '32');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('4', 'LPS 20', TO_DATE('2024-01-13', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '33');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('5', 'LPS 100', TO_DATE('2024-01-14', 'YYYY-MM-DD'), 'No realizar el pago de libro', '34');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('6', 'LPS 200', TO_DATE('2024-01-15', 'YYYY-MM-DD'), 'Extraviar libro', '35');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('7', 'LPS 20', TO_DATE('2024-01-16', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '36');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('8', 'LPS 100', TO_DATE('2024-01-17', 'YYYY-MM-DD'), 'No realizar el pago de libro', '37');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('9', 'LPS 200', TO_DATE('2024-01-18', 'YYYY-MM-DD'), 'Extraviar libro', '38');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('10', 'LPS 20', TO_DATE('2024-01-19', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '39');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('12', 'LPS 200', TO_DATE('2024-01-21', 'YYYY-MM-DD'), 'Extraviar libro', '41');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('13', 'LPS 20', TO_DATE('2024-01-22', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '42');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('15', 'LPS 200', TO_DATE('2024-01-24', 'YYYY-MM-DD'), 'Extraviar libro', '44');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('16', 'LPS 20', TO_DATE('2024-01-25', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '45');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('17', 'LPS 100', TO_DATE('2024-01-26', 'YYYY-MM-DD'), 'No realizar el pago de libro', '46');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('18', 'LPS 200', TO_DATE('2024-01-27', 'YYYY-MM-DD'), 'Extraviar libro', '47');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('19', 'LPS 20', TO_DATE('2024-01-28', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '48');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('20', 'LPS 100', TO_DATE('2024-01-29', 'YYYY-MM-DD'), 'No realizar el pago de libro', '49');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('21', 'LPS 200', TO_DATE('2024-01-30', 'YYYY-MM-DD'), 'Extraviar libro', '50');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('22', 'LPS 20', TO_DATE('2024-01-31', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '30');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('23', 'LPS 100', TO_DATE('2024-02-01', 'YYYY-MM-DD'), 'No realizar el pago de libro', '31');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('24', 'LPS 200', TO_DATE('2024-02-02', 'YYYY-MM-DD'), 'Extraviar libro', '32');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('25', 'LPS 20', TO_DATE('2024-02-03', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '33');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('26', 'LPS 100', TO_DATE('2024-02-04', 'YYYY-MM-DD'), 'No realizar el pago de libro', '34');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('27', 'LPS 200', TO_DATE('2024-02-05', 'YYYY-MM-DD'), 'Extraviar libro', '35');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('28', 'LPS 20', TO_DATE('2024-02-06', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '36');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('29', 'LPS 100', TO_DATE('2024-02-07', 'YYYY-MM-DD'), 'No realizar el pago de libro', '37');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('30', 'LPS 200', TO_DATE('2024-02-08', 'YYYY-MM-DD'), 'Extraviar libro', '38');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('31', 'LPS 20', TO_DATE('2024-02-09', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '39');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('32', 'LPS 100', TO_DATE('2024-02-10', 'YYYY-MM-DD'), 'No realizar el pago de libro', '40');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('33', 'LPS 200', TO_DATE('2024-02-11', 'YYYY-MM-DD'), 'Extraviar libro', '41');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('34', 'LPS 20', TO_DATE('2024-02-12', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '42');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('35', 'LPS 100', TO_DATE('2024-02-13', 'YYYY-MM-DD'), 'No realizar el pago de libro', '43');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('36', 'LPS 200', TO_DATE('2024-02-14', 'YYYY-MM-DD'), 'Extraviar libro', '44');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('37', 'LPS 20', TO_DATE('2024-02-15', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '45');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('38', 'LPS 100', TO_DATE('2024-02-16', 'YYYY-MM-DD'), 'No realizar el pago de libro', '46');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('39', 'LPS 200', TO_DATE('2024-02-17', 'YYYY-MM-DD'), 'Extraviar libro', '47');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('40', 'LPS 20', TO_DATE('2024-02-18', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '48');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('41', 'LPS 100', TO_DATE('2024-02-19', 'YYYY-MM-DD'), 'No realizar el pago de libro', '49');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('42', 'LPS 200', TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'Extraviar libro', '50');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('43', 'LPS 20', TO_DATE('2024-02-21', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '30');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('44', 'LPS 100', TO_DATE('2024-02-22', 'YYYY-MM-DD'), 'No realizar el pago de libro', '31');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('45', 'LPS 200', TO_DATE('2024-02-23', 'YYYY-MM-DD'), 'Extraviar libro', '32');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('46', 'LPS 20', TO_DATE('2024-02-24', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '33');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('47', 'LPS 100', TO_DATE('2024-02-25', 'YYYY-MM-DD'), 'No realizar el pago de libro', '34');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('48', 'LPS 200', TO_DATE('2024-02-26', 'YYYY-MM-DD'), 'Extraviar libro', '35');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('49', 'LPS 20', TO_DATE('2024-02-27', 'YYYY-MM-DD'), 'No realizar el pago de membresía', '36');
INSERT INTO multa (id, monto, fechaPago, motivo, usuario_id) VALUES ('50', 'LPS 100', TO_DATE('2024-02-28', 'YYYY-MM-DD'), 'No realizar el pago de libro', '37');
