
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('1', 'Me encantaría ver más detalles sobre el mundo mágico en el próximo libro.', '1');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('2', 'Sería genial si hubiera una expansión sobre los personajes secundarios.', '2');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('3', 'Podrían explorar más la historia de los fundadores de Hogwarts.', '3');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('4', 'Más escenas de acción y menos descripciones largas, por favor.', '4');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('5', 'Añadir más personajes femeninos fuertes a la trama.', '5');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('6', 'Incluir más detalles sobre la historia de los elfos y su cultura.', '6');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('7', 'Explorar más sobre las tierras del sur y el este de la Tierra Media.', '7');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('8', 'Más desarrollo de personajes secundarios para enriquecer la trama.', '8');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('9', 'Explorar más el trasfondo de los villanos para hacerlos más complejos.', '9');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('10', 'Incluir más giros inesperados en la trama para mantener el suspense.', '10');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('11', 'Desarrollar más las historias secundarias para profundizar en el universo.', '11');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('12', 'Más interacciones entre los personajes principales para fortalecer la trama.', '12');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('13', 'Podrían variar un poco más las tramas de asesinato para no ser tan predecibles.', '13');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('14', 'Explorar más en profundidad los personajes secundarios de la trama.', '14');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('15', 'Incluir más giros sorpresivos en la resolución de los casos.', '15');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('16', 'Desarrollar más el contexto histórico y social en los que se desarrollan las historias.', '16');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('17', 'Incluir más capítulos desde la perspectiva de personajes secundarios.', '17');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('18', 'Más desarrollo de los conflictos políticos entre las casas.', '18');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('19', 'Reducir un poco la extensión de los capítulos para mantener el ritmo.', '19');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('20', 'Explorar más sobre los eventos históricos mencionados en la serie.', '20');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('21', 'Incluir más casos que desafíen las habilidades deductivas de Sherlock Holmes.', '21');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('22', 'Más interacción entre Holmes y Watson para desarrollar mejor su relación.', '22');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('23', 'Explorar más sobre el contexto histórico en el que se sitúan los casos.', '23');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('24', 'Agregar más variedad en los tipos de crimen y misterio.', '24');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('25', 'Desarrollar más la interacción entre la robótica y la ética en la trama.', '25');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('26', 'Incluir más personajes con roles activos en la trama.', '26');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('27', 'Más exploración de las sociedades futuras y sus estructuras.', '27');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('28', 'Agregar más detalles sobre la tecnología y cómo impacta a la sociedad.', '28');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('29', 'Explorar más los pensamientos internos del protagonista para profundizar en su carácter.', '29');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('30', 'Más desarrollo de los personajes secundarios y sus historias.', '30');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('31', 'Incluir tramas secundarias que enriquezcan la historia principal.', '31');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('32', 'Más profundidad en los conflictos sociales y familiares.', '32');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('33', 'Más aventuras en los libros para mantener la emoción.', '33');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('34', 'Incluir más humor y crítica social en las tramas.', '34');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('35', 'Incluir más diálogos y menos narración para un ritmo más rápido.', '35');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('36', 'Explorar más los conflictos internos de los personajes.', '36');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('37', 'Desarrollar más los escenarios para crear una atmósfera más inmersiva.', '37');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('38', 'Más enfoque en los personajes principales y menos en los secundarios.', '38');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('39', 'Reducir la longitud de las novelas para mantener el interés.', '39');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('40', 'Agregar más resolución en las tramas secundarias.', '40');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('41', 'Más enfoque en los eventos históricos y su impacto en los personajes.', '41');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('42', 'Incluir más perspectivas de los personajes secundarios.', '42');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('43', 'Más desarrollo en la trama principal para mantener el interés.', '43');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('44', 'Incluir más estructura en la narrativa para facilitar la comprensión.', '44');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('45', 'Explorar más las relaciones entre los personajes.', '45');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('46', 'Más claridad en la narrativa para facilitar la lectura.', '46');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('47', 'Agregar más detalles sobre los entornos y los personajes.', '47');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('48', 'Más desarrollo de la trama para evitar la sensación de desconexión.', '48');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('49', 'Explorar más el contexto en el que se desarrolla la historia.', '49');
INSERT INTO sugerencia (id, contenido, usuario_id) VALUES ('50', 'Incluir más diálogo y menos monólogo interior.', '50');
